apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-cluster
  region: ap-northeast-2

managedNodeGroups:
  - name: eks-node-group
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    iam:
      instanceRoleARN: arn:aws:iam::730335509885:role/eks-node-role
    privateNetworking: true
    labels:
      role: worker
    tags:
      nodegroup-role: worker

