apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: ${CLUSTER_NAME}
  region: ${AWS_REGION}

addons:
  - name: vpc-cni
    version: latest
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
    wellKnownPolicies:
      awsLoadBalancerController: true

vpc:
  id: ${VPC_ID}
  subnets:
    public:
      ${AWS_REGION}a:
        id: ${PUBLIC_SUBNET_ID_A}
      ${AWS_REGION}c:
        id: ${PUBLIC_SUBNET_ID_C}
    private:
      ${AWS_REGION}a:
        id: ${PRIVATE_SUBNET_ID_A}
      ${AWS_REGION}c:
        id: ${PRIVATE_SUBNET_ID_C}

managedNodeGroups:
  - name: ${NODE_GROUP_NAME}
    instanceType: ${INSTANCE_TYPE}
    desiredCapacity: ${DESIRED_CAPACITY}
    minSize: ${MIN_SIZE}
    maxSize: ${MAX_SIZE}
    iam:
      instanceRoleARN: ${NODE_ROLE_ARN}
    privateNetworking: true
    labels:
      role: worker
    tags:
      nodegroup-role: worker
